/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTimesheetRouteImport } from './routes/_authenticated/timesheet'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedSignalsRouteImport } from './routes/_authenticated/signals'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedExecRouteImport } from './routes/_authenticated/exec'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicHooksFridayDraftsRouteImport } from './routes/api/public/hooks/friday-drafts'
import { Route as ApiPublicHooksActivitySignalRouteImport } from './routes/api/public/hooks/activity-signal'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimesheetRoute = AuthenticatedTimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSignalsRoute = AuthenticatedSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExecRoute = AuthenticatedExecRouteImport.update({
  id: '/exec',
  path: '/exec',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHooksFridayDraftsRoute =
  ApiPublicHooksFridayDraftsRouteImport.update({
    id: '/api/public/hooks/friday-drafts',
    path: '/api/public/hooks/friday-drafts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksActivitySignalRoute =
  ApiPublicHooksActivitySignalRouteImport.update({
    id: '/api/public/hooks/activity-signal',
    path: '/api/public/hooks/activity-signal',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exec': typeof AuthenticatedExecRoute
  '/hr': typeof AuthenticatedHrRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/timesheet': typeof AuthenticatedTimesheetRoute
  '/api/public/hooks/activity-signal': typeof ApiPublicHooksActivitySignalRoute
  '/api/public/hooks/friday-drafts': typeof ApiPublicHooksFridayDraftsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exec': typeof AuthenticatedExecRoute
  '/hr': typeof AuthenticatedHrRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/timesheet': typeof AuthenticatedTimesheetRoute
  '/api/public/hooks/activity-signal': typeof ApiPublicHooksActivitySignalRoute
  '/api/public/hooks/friday-drafts': typeof ApiPublicHooksFridayDraftsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exec': typeof AuthenticatedExecRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRoute
  '/_authenticated/signals': typeof AuthenticatedSignalsRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/_authenticated/timesheet': typeof AuthenticatedTimesheetRoute
  '/api/public/hooks/activity-signal': typeof ApiPublicHooksActivitySignalRoute
  '/api/public/hooks/friday-drafts': typeof ApiPublicHooksFridayDraftsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/exec'
    | '/hr'
    | '/manager'
    | '/signals'
    | '/teams'
    | '/timesheet'
    | '/api/public/hooks/activity-signal'
    | '/api/public/hooks/friday-drafts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/exec'
    | '/hr'
    | '/manager'
    | '/signals'
    | '/teams'
    | '/timesheet'
    | '/api/public/hooks/activity-signal'
    | '/api/public/hooks/friday-drafts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/exec'
    | '/_authenticated/hr'
    | '/_authenticated/manager'
    | '/_authenticated/signals'
    | '/_authenticated/teams'
    | '/_authenticated/timesheet'
    | '/api/public/hooks/activity-signal'
    | '/api/public/hooks/friday-drafts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicHooksActivitySignalRoute: typeof ApiPublicHooksActivitySignalRoute
  ApiPublicHooksFridayDraftsRoute: typeof ApiPublicHooksFridayDraftsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timesheet': {
      id: '/_authenticated/timesheet'
      path: '/timesheet'
      fullPath: '/timesheet'
      preLoaderRoute: typeof AuthenticatedTimesheetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/signals': {
      id: '/_authenticated/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AuthenticatedSignalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exec': {
      id: '/_authenticated/exec'
      path: '/exec'
      fullPath: '/exec'
      preLoaderRoute: typeof AuthenticatedExecRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/friday-drafts': {
      id: '/api/public/hooks/friday-drafts'
      path: '/api/public/hooks/friday-drafts'
      fullPath: '/api/public/hooks/friday-drafts'
      preLoaderRoute: typeof ApiPublicHooksFridayDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/activity-signal': {
      id: '/api/public/hooks/activity-signal'
      path: '/api/public/hooks/activity-signal'
      fullPath: '/api/public/hooks/activity-signal'
      preLoaderRoute: typeof ApiPublicHooksActivitySignalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExecRoute: typeof AuthenticatedExecRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRoute
  AuthenticatedSignalsRoute: typeof AuthenticatedSignalsRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedTimesheetRoute: typeof AuthenticatedTimesheetRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExecRoute: AuthenticatedExecRoute,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRoute,
  AuthenticatedSignalsRoute: AuthenticatedSignalsRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedTimesheetRoute: AuthenticatedTimesheetRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicHooksActivitySignalRoute: ApiPublicHooksActivitySignalRoute,
  ApiPublicHooksFridayDraftsRoute: ApiPublicHooksFridayDraftsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
